db:
  host: localhost
  port: 3306
  database: lan-auth
  username: root
  password:
  dialect: mysql
  logging: false

log:
  console:
    level: debug
  file:
    silent: true
    level: debug
    filename: console.log
    maxsize: 3000000
    maxFiles: 10
    json: false
  db:
    silent: false

lanApi:
  key: default
  baseUrl: http://127.0.0.1:8001/
  lanNumber:
    cache: 1800 #In seconds

admin:
  key: default
  enable: true